// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission09_murdodav.Models;

namespace Mission09_murdodav.Migrations
{
    [DbContext(typeof(BookstoreContext))]
    [Migration("20230330232957_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mission09_murdodav.Models.Book", b =>
                {
                    b.Property<long>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1L,
                            Author = "Victor Hugo",
                            Category = "Classic",
                            Classification = "Fiction",
                            Isbn = "978-0451419439",
                            PageCount = 1488,
                            Price = 9.9499999999999993,
                            Publisher = "Signet",
                            Title = "Les Miserables"
                        },
                        new
                        {
                            BookId = 2L,
                            Author = "Doris Kearns Goodwin",
                            Category = "Biography",
                            Classification = "Non-Fiction",
                            Isbn = "978-0743270755",
                            PageCount = 944,
                            Price = 14.58,
                            Publisher = "Simon & Schuster",
                            Title = "Team of Rivals"
                        },
                        new
                        {
                            BookId = 3L,
                            Author = "Alice Schroeder",
                            Category = "Biography",
                            Classification = "Non-Fiction",
                            Isbn = "978-0553384611",
                            PageCount = 832,
                            Price = 21.539999999999999,
                            Publisher = "Bantam",
                            Title = "The Snowball"
                        },
                        new
                        {
                            BookId = 4L,
                            Author = "Ronald C. White",
                            Category = "Biography",
                            Classification = "Non-Fiction",
                            Isbn = "978-0812981254",
                            PageCount = 864,
                            Price = 11.609999999999999,
                            Publisher = "Random House",
                            Title = "American Ulysses"
                        });
                });

            modelBuilder.Entity("Mission09_murdodav.Models.BookPurchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Zip")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PurchaseId");

                    b.ToTable("BookPurchases");
                });

            modelBuilder.Entity("Mission09_murdodav.Models.CartItem", b =>
                {
                    b.Property<int>("LineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long?>("BookId")
                        .HasColumnType("bigint");

                    b.Property<int?>("BookPurchasePurchaseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("LineID");

                    b.HasIndex("BookId");

                    b.HasIndex("BookPurchasePurchaseId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("Mission09_murdodav.Models.CartItem", b =>
                {
                    b.HasOne("Mission09_murdodav.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");

                    b.HasOne("Mission09_murdodav.Models.BookPurchase", null)
                        .WithMany("Lines")
                        .HasForeignKey("BookPurchasePurchaseId");
                });
#pragma warning restore 612, 618
        }
    }
}
